name: Deploy docs
on:
  push:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/deploy-docs.yml'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'docs/*'
      - 'mkdocs.yml'

  pull_request:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/deploy-docs.yml'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'docs/*'
      - 'mkdocs.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Max fetch depth (full history of files)

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
          cache: "poetry"
          cache-dependency-path: poetry.lock

      - name: Install dependencies
        run: poetry install --no-root

      - name: Buld docs
        run: poetry run mkdocs build

      - name: Deploy docs
        if: github.event_name != 'pull_request'
        run: poetry run mkdocs gh-deploy --force
